# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47cc84035717d14f581b715286f1c337c613ddb75acd5693eb6c410b3e153053ef85c81024057920aebacb6d0a568c092d82d56c2c1b1421e21b3a04e071423e

test:
  secret_key_base: ea469e52ab66c9d65d9d4e1972622ccf41f98e9cc79ec74afb72767021c1505365eee9fea9a50c2d39f17c3c43875cdf213c030722c5f360996093fc1f8bb5ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
